CREATE SEQUENCE CAIXAS_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE SEQUENCE FILIAL_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE SEQUENCE EQUIPAMENTO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE SEQUENCE PRODUTO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE SEQUENCE CATEGORIA_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE SEQUENCE MARCA_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE SEQUENCE SOLICITACAO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;


CREATE TABLE CLIENTE (
    CPF CHAR(11),
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(40),
    PONTOS INTEGER
);

CREATE TABLE TELEFONE_CLIENTE (
    CPF_CLIENTE CHAR(11),
    TELEFONES CHAR(9)
);

CREATE TABLE ENDERECO (
    CPF_CLIENTE CHAR(11),
    RUA VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(4),
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL
);

CREATE TABLE ORDEM_COMPRA (
    NOTA_FISCAL CHAR(44) NOT NULL,
    DATA_COMPRA DATE NOT NULL, 
    ID_CAIXA INTEGER NOT NULL,
    CPF_CLIENTE CHAR(11) NOT NULL
);

CREATE TABLE CAIXA (
    NUMERO_DO_CAIXA INTEGER DEFAULT CAIXAS_SEQ.NEXTVAL,
    ID_FILIAL INTEGER NOT NULL
);

CREATE TABLE FILIAL (
    CODIGO_DE_IDENTIFICACAO INTEGER DEFAULT FILIAL_SEQ.NEXTVAL,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(200),
    TELEFONE VARCHAR(13),
    ID_DO_GERENTE CHAR(9) NOT NULL
);

CREATE TABLE NOTA_FISCAL (
    NUMERO CHAR(44),
    CNPJ CHAR(14) NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    DATA DATE NOT NULL,
    VALOR_POR_ITEM DECIMAL(10, 2),
    ID_DE_SOLICITACAO INTEGER NOT NULL
);

CREATE TABLE EQUIPAMENTO (
    IDENTIFICADOR INTEGER DEFAULT EQUIPAMENTO_SEQ.NEXTVAL,
    DESCRICAO VARCHAR(500),
    NUMERO_DO_CAIXA INTEGER NOT NULL
);

CREATE TABLE REALIZA_RECLAMACAO (
    CPF CHAR(11),
    ID_FILIAL INTEGER NOT NULL,
    DATA_E_HORA TIMESTAMP DEFAULT SYSDATE,
    DESCRICAO VARCHAR(500) NOT NULL
);

CREATE TABLE REALIZA_MANUTENCAO (
    ID_EQUIPAMENTO INTEGER,
    MATRICULA_FUNCIONARIO CHAR(9) NOT NULL,
    DATA_E_HORA TIMESTAMP DEFAULT SYSDATE,
    CUSTO DECIMAL(10, 2)
);

CREATE TABLE FUNCIONARIO (
    MATRICULA CHAR(9),
    CPF CHAR(11) NOT NULL,
    IDENTIDADE CHAR(7) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(200),
    SALARIO NUMBER(9,2) NOT NULL,
    FUNCAO VARCHAR(40) NOT NULL,
    ID_FILIAL INTEGER NOT NULL,
    COD_GERENTE CHAR(9)
);

CREATE TABLE TELEFONES_FUNCIONARIO (
    MATRICULA_FUNCIONARIO CHAR(9),
    TELEFONE CHAR(9) NOT NULL
);

CREATE TABLE FORNECEDOR (
    CNPJ CHAR(14),
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(200),
    EMAIL VARCHAR(40),
    SITE VARCHAR(30),
    ID_CATEGORIA INTEGER NOT NULL
);

CREATE TABLE TELEFONES_FORNECEDOR (
    CNPJ CHAR(14),
    TELEFONE CHAR(9)
);

CREATE TABLE DEPENDENTE (
    CPF CHAR(11),
    DATA_DE_NASCIMENTO DATE NOT NULL, 
    MATRICULA_FUNCIONARIO CHAR(9) NOT NULL,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUTO (
    CODIGO_DE_IDENTIFICACAO INTEGER DEFAULT PRODUTO_SEQ.NEXTVAL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(500),
    MARGEM_DE_LUCRO_MINIMA DECIMAL(10,2) NOT NULL, 
    ID_CATEGORIA INTEGER NOT NULL,
    ID_MARCA INTEGER NOT NULL
);

CREATE TABLE CATEGORIA (
    IDENTIFICADOR INTEGER DEFAULT CATEGORIA_SEQ.NEXTVAL,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE MARCA (
    IDENTIFICADOR INTEGER DEFAULT MARCA_SEQ.NEXTVAL,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE SOLICITACAO (
    IDENTIFICADOR INTEGER  DEFAULT SOLICITACAO_SEQ.NEXTVAL,
    DATA_SOLICITACAO DATE NOT NULL,
    DATA_PREVISTA_P_ENTREGA DATE NOT NULL,
    DATA_DA_ENTREGA DATE NOT NULL,
    VALOR_DA_COMPRA DECIMAL(10,2) NOT NULL,
    PRAZO_P_PAGAMENTO_EM_DIAS INTEGER NOT NULL,
    ID_FILIAL INTEGER NOT NULL,
    CNPJ_FORNECEDOR CHAR(14) NOT NULL
);


ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF);

ALTER TABLE TELEFONE_CLIENTE ADD CONSTRAINT PK_TELEFONE_CLIENTE PRIMARY KEY (CPF_CLIENTE, TELEFONES);

ALTER TABLE ENDERECO ADD CONSTRAINT PK_ENDERECO PRIMARY KEY (CPF_CLIENTE);

ALTER TABLE CAIXA ADD CONSTRAINT PK_CAIXA PRIMARY KEY (NUMERO_DO_CAIXA);

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT PK_ORDEM_COMPRA PRIMARY KEY (NOTA_FISCAL);

ALTER TABLE FILIAL ADD CONSTRAINT PK_FILIAL  PRIMARY KEY (CODIGO_DE_IDENTIFICACAO);

ALTER TABLE NOTA_FISCAL ADD CONSTRAINT PK_NOTA_FISCAL PRIMARY KEY (NUMERO);

ALTER TABLE EQUIPAMENTO ADD CONSTRAINT PK_EQUIPAMENTO PRIMARY KEY (IDENTIFICADOR);

ALTER TABLE REALIZA_RECLAMACAO ADD CONSTRAINT PK_REALIZA_RECLAMACAO PRIMARY KEY (CPF, ID_FILIAL, DATA_E_HORA);

ALTER TABLE REALIZA_MANUTENCAO ADD CONSTRAINT PK_REALIZA_MANUTENCAO PRIMARY KEY (ID_EQUIPAMENTO, MATRICULA_FUNCIONARIO, DATA_E_HORA);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_MATRICULA PRIMARY KEY (MATRICULA);

ALTER TABLE TELEFONES_FUNCIONARIO ADD CONSTRAINT PK_TELEFONES_FUNCIONARIO PRIMARY KEY (MATRICULA_FUNCIONARIO, TELEFONE);

ALTER TABLE FORNECEDOR ADD CONSTRAINT PK_FORNECEDOR PRIMARY KEY (CNPJ);

ALTER TABLE TELEFONES_FORNECEDOR ADD CONSTRAINT PK_TELEFONES_FORNECEDOR PRIMARY KEY (CNPJ, TELEFONE);

ALTER TABLE DEPENDENTE ADD CONSTRAINT PK_DEPENDENTE PRIMARY KEY (CPF);

ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO_DE_IDENTIFICACAO);

ALTER TABLE MARCA ADD CONSTRAINT PK_MARCA PRIMARY KEY (IDENTIFICADOR);

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (IDENTIFICADOR);

ALTER TABLE SOLICITACAO ADD CONSTRAINT PK_SOLICITACAO PRIMARY KEY (IDENTIFICADOR);


ALTER TABLE TELEFONE_CLIENTE ADD CONSTRAINT FK_TELEFONES_CLIENTE FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTE(CPF) INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTE(CPF) INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE CAIXA ADD CONSTRAINT FK_CAIXA_FILIAL FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL(CODIGO_DE_IDENTIFICACAO) INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT FK_ORDEM_COMPRA_CAIXA FOREIGN KEY (ID_CAIXA) REFERENCES CAIXA(NUMERO_DO_CAIXA) INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT FK_ORDEM_COMPRA_NOTA_FISCAL FOREIGN KEY(NOTA_FISCAL) REFERENCES NOTA_FISCAL(NUMERO) INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT FK_ORDEM_CLIENTE FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTE(CPF) INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE FILIAL ADD CONSTRAINT FK_FILIAL_GERENTE FOREIGN KEY (ID_DO_GERENTE) REFERENCES FUNCIONARIO(MATRICULA);

ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_NOTA_FISCAL_SOLICITACAO FOREIGN KEY (ID_DE_SOLICITACAO) REFERENCES SOLICITACAO(IDENTIFICADOR);

ALTER TABLE EQUIPAMENTO ADD CONSTRAINT FK_EQUIPAMENTO_CAIXA FOREIGN KEY (NUMERO_DO_CAIXA) REFERENCES CAIXA(NUMERO_DO_CAIXA);

ALTER TABLE REALIZA_RECLAMACAO ADD CONSTRAINT FK_REALIZA_RECLAMACAO_CLIENTE FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF);

ALTER TABLE REALIZA_RECLAMACAO ADD CONSTRAINT FK_REALIZA_RECLAMACAO_FILIAL FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL(CODIGO_DE_IDENTIFICACAO); 

ALTER TABLE REALIZA_MANUTENCAO ADD CONSTRAINT FK_REALIZA_MANUTENCAO_EQUIPAMENTO FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES EQUIPAMENTO(IDENTIFICADOR);

ALTER TABLE REALIZA_MANUTENCAO ADD CONSTRAINT FK_REALIZA_MANUTENCAO_FUNCIONARIO FOREIGN KEY (MATRICULA_FUNCIONARIO) REFERENCES FUNCIONARIO(MATRICULA);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_FUNCIONARIO FOREIGN KEY (COD_GERENTE) REFERENCES FUNCIONARIO(MATRICULA);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_FILIAL FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL(CODIGO_DE_IDENTIFICACAO);

ALTER TABLE TELEFONES_FUNCIONARIO ADD CONSTRAINT FK_TELEFONES_FUNCIONARIO_FUNCIONARIO FOREIGN KEY (MATRICULA_FUNCIONARIO) REFERENCES FUNCIONARIO(MATRICULA);

ALTER TABLE FORNECEDOR ADD CONSTRAINT FK_FORNECEDOR_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(IDENTIFICADOR);

ALTER TABLE TELEFONES_FORNECEDOR ADD CONSTRAINT FK_TELEFONES_FORNECEDOR_FORNECEDOR FOREIGN KEY (CNPJ) REFERENCES FORNECEDOR(CNPJ);

ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_FUNCIONARIO FOREIGN KEY (MATRICULA_FUNCIONARIO) REFERENCES FUNCIONARIO(MATRICULA);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(IDENTIFICADOR);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(IDENTIFICADOR);

ALTER TABLE SOLICITACAO ADD CONSTRAINT FK_SOLICITACAO_FILIAL FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL(CODIGO_DE_IDENTIFICACAO);

ALTER TABLE SOLICITACAO ADD CONSTRAINT FK_SOLICITACAO_FORNECEDOR FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ);


ALTER TABLE NOTA_FISCAL ADD CONSTRAINT CK_QUANTIDADE_MAIOR_QUE_ZERO CHECK (QUANTIDADE > 0);

ALTER TABLE NOTA_FISCAL ADD CONSTRAINT CK_VALOR_MAIOR_QUE_ZERO CHECK (VALOR_POR_ITEM >= 0);

ALTER TABLE PRODUTO ADD CONSTRAINT CK_PRODUTO_LUCRO_MAIOR_QUE_ZERO CHECK (MARGEM_DE_LUCRO_MINIMA > 0); 

ALTER TABLE SOLICITACAO ADD CONSTRAINT CK_SOLICITACAO_VALOR_MAIOR_QUE_ZERO CHECK (VALOR_DA_COMPRA > 0); 


--  exclusão das tabelas
DROP TABLE CAIXA CASCADE CONSTRAINTS;

DROP TABLE CATEGORIA CASCADE CONSTRAINTS;

DROP TABLE CLIENTE CASCADE CONSTRAINTS;

DROP TABLE DEPENDENTE CASCADE CONSTRAINTS;

DROP TABLE ENDERECO CASCADE CONSTRAINTS;

DROP TABLE EQUIPAMENTO CASCADE CONSTRAINTS;

DROP TABLE FILIAL CASCADE CONSTRAINTS;

DROP TABLE FORNECEDOR CASCADE CONSTRAINTS;

DROP TABLE FUNCIONARIO CASCADE CONSTRAINTS;

DROP TABLE MARCA CASCADE CONSTRAINTS;

DROP TABLE NOTA_FISCAL CASCADE CONSTRAINTS;

DROP TABLE ORDEM_COMPRA CASCADE CONSTRAINTS;

DROP TABLE PRODUTO CASCADE CONSTRAINTS;

DROP TABLE REALIZA_MANUTENCAO CASCADE CONSTRAINTS;

DROP TABLE REALIZA_RECLAMACAO CASCADE CONSTRAINTS;

DROP TABLE SOLICITACAO CASCADE CONSTRAINTS;

DROP TABLE TELEFONES_FORNECEDOR CASCADE CONSTRAINTS;

DROP TABLE TELEFONES_FUNCIONARIO CASCADE CONSTRAINTS;

DROP TABLE TELEFONE_CLIENTE CASCADE CONSTRAINTS;


DROP SEQUENCE CAIXAS_SEQ;

DROP SEQUENCE CATEGORIA_SEQ;

DROP SEQUENCE EQUIPAMENTO_SEQ;

DROP SEQUENCE FILIAL_SEQ;

DROP SEQUENCE MARCA_SEQ;

DROP SEQUENCE PRODUTO_SEQ;

DROP SEQUENCE SOLICITACAO_SEQ;