CREATE TABLE CLIENTE(
    CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    PONTOS_CRM NUMBER,
    RUA VARCHAR(100),
    NUM NUMBER,
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(50),
    BAIRRO VARCHAR(50)
);

CREATE TABLE TELEFONE_CLIENTE(
    CLI_CPF VARCHAR(15),
    TELEFONE VARCHAR(20),
    PRIMARY KEY (CLI_CPF, TELEFONE)
);

CREATE TABLE RECLAMACAO(
    CLI_CPF VARCHAR(15),
    FIL_CODIGO NUMBER,
    DATA_E_HORA TIMESTAMP,
    DESCRICAO VARCHAR(500),
    PRIMARY KEY (CLI_CPF, FIL_CODIGO)
);

CREATE TABLE FILIAL(
    CODIGO NUMBER PRIMARY KEY,
    NOME VARCHAR(100),
    ENDERECO VARCHAR(100),
    TELEFONE VARCHAR(20),
    GERENTE_MATRICULA NUMBER
);

CREATE TABLE FUNCIONARIO(
    MATRICULA NUMBER PRIMARY KEY,
    CPF VARCHAR(15),
    IDENTIDADE VARCHAR(15),
    NOME VARCHAR(100),
    ENDERECO VARCHAR(100),
    SALARIO NUMBER,
    FUNCAO VARCHAR(50),
    FIL_CODIGO NUMBER,
    SUPERVISOR_MATRICULA NUMBER
);

CREATE TABLE TELEFONE_FUNCIONARIO(
    FUN_MATRICULA NUMBER,
    TELEFONE VARCHAR(20),
    PRIMARY KEY (FUN_MATRICULA, TELEFONE)
);

CREATE TABLE DEPENDENTE(
    DEP_CPF VARCHAR(15),
    FUN_MATRICULA NUMBER,
    DATA_DE_NASCIMENTO DATE,
    NOME VARCHAR(100),
    PRIMARY KEY (FUN_MATRICULA, DEP_CPF)
);

CREATE TABLE MANUTENCAO(
    FUN_MATRICULA NUMBER,
    EQU_IDENTIFICADOR NUMBER,
    NUMERO_DO_CAIXA NUMBER,
    DATA_E_HORA TIMESTAMP,
    CUSTO NUMBER,
    PRIMARY KEY (FUN_MATRICULA, EQU_IDENTIFICADOR, NUMERO_DO_CAIXA)
);

CREATE TABLE EQUIPAMENTO(
    IDENTIFICADOR NUMBER,
    NUMERO_DO_CAIXA NUMBER,
    DESCRICAO VARCHAR(500),
    PRIMARY KEY (IDENTIFICADOR, NUMERO_DO_CAIXA)
);

CREATE TABLE CAIXA(
    NUMERO_DO_CAIXA NUMBER PRIMARY KEY,
    FIL_CODIGO NUMBER
);

CREATE TABLE ORDEM_DE_COMPRA(
    NUMERO_NOTA_FISCAL NUMBER PRIMARY KEY,
    DATA_E_HORA_DA_VENDA TIMESTAMP,
    CAI_NUMERO NUMBER,
    CLI_CPF VARCHAR(15),
    FIL_CODIGO NUMBER,
    FUN_MATRICULA NUMBER
);

CREATE TABLE ITEM(
    IDENTIFICADOR NUMBER,
    ODC_NUMERO_NOTA NUMBER,
    QUANTIDADE NUMBER,
    PRECO_PRODUTO NUMBER,
    DESCONTO NUMBER,
    PRO_CODIGO_IDENTIFICACAO NUMBER,
    NTF_NUMERO NUMBER,
    PRIMARY KEY (IDENTIFICADOR, ODC_NUMERO_NOTA)
);

CREATE TABLE PRODUTO(
    CODIGO_DE_IDENTIFICACAO NUMBER PRIMARY KEY,
    NOME VARCHAR(50),
    DESCRICAO VARCHAR(500),
    MARGEM_DE_LUCRO_MINIMA NUMBER,
    FIL_CODIGO NUMBER,
    QUANTIDADE NUMBER,
    DATA_DE_VALIDADE DATE,
    PRECO_DE_VENDA NUMBER,
    PRECO_DE_COMPRA NUMBER,
    DATA_DE_COMPRA DATE,
    MAR_IDENTIFICADOR NUMBER,
    CAT_IDENTIFICADOR NUMBER
);

CREATE TABLE MARCA(
    IDENTIFICADOR NUMBER PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE FORNECEDOR(
    CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(100),
    ENDERECO VARCHAR(100),
    EMAIL VARCHAR(50),
    SITE VARCHAR(100),
    CAT_IDENTIFICADOR NUMBER
);

CREATE TABLE NOTA_FISCAL(
    NUMERO NUMBER PRIMARY KEY,
    CNPJ VARCHAR(20),
    QUANTIDADE NUMBER,
    DATA DATE,
    VALOR_POR_ITEM NUMBER,
    SOL_IDENTIFICADOR NUMBER
);

CREATE TABLE SOLICITACAO(
    IDENTIFICADOR NUMBER PRIMARY KEY,
    DATA_DE_SOLICITACAO DATE,
    DATA_PREVISTA_ENTREGA DATE,
    DATA_DA_ENTREGA DATE,
    VALOR_DA_COMPRA NUMBER,
    PRAZO_PAGAMENTO DATE,
    FIL_CODIGO NUMBER,
    FOR_CNPJ VARCHAR(20)
);

CREATE TABLE CATEGORIA(
    IDENTIFICADOR NUMBER PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE TELEFONE_FORNECEDOR(
    FOR_CNPJ VARCHAR(20),
    TELEFONE VARCHAR(50),
    PRIMARY KEY (FOR_CNPJ, TELEFONE)
);

/*FK (CLI_CPF) REF. CLIENTE(CPF)*/
ALTER TABLE TELEFONE_CLIENTE ADD CONSTRAINT FK_CLICPF_IN_TELEFONE FOREIGN KEY (CLI_CPF) REFERENCES CLIENTE(CPF);
/*FK (CLI_CPF) REF. CLIENTE(CPF)*/
ALTER TABLE RECLAMACAO ADD CONSTRAINT FK_CLICPF_IN_RECLAMACAO FOREIGN KEY (CLI_CPF) REFERENCES CLIENTE(CPF);
/*FK (FIL_CODIGO) REF. FILIAL(CODIGO)*/
ALTER TABLE RECLAMACAO ADD CONSTRAINT FK_FILCODIGO_IN_RECLAMACAO FOREIGN KEY (FIL_CODIGO) REFERENCES FILIAL(CODIGO);
/*FK (GERENTE_MATRICULA) REF. FUNCIONARIO(MATRICULA)*/
ALTER TABLE FILIAL ADD CONSTRAINT FK_GERENTEMATRICULA_IN_FILAL FOREIGN KEY (GERENTE_MATRICULA) REFERENCES FUNCIONARIO(MATRICULA);
/*FK (SUPERVISOR_MATRICULA) REF. FUNCIONARIO(MATRICULA)*/
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_SUPERVISOR_IN_FUNCIONARIO FOREIGN KEY (SUPERVISOR_MATRICULA) REFERENCES FUNCIONARIO(MATRICULA);
/*FK (FIL_CODIGO) REF. FILIAL(CODIGO)*/
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FILCOD_IN_FUNCIONARIO FOREIGN KEY (FIL_CODIGO) REFERENCES FILIAL(CODIGO);
/*FK (FUN_MATRICULA) REF. FUNCIONARIO(MATRICULA)*/
ALTER TABLE TELEFONE_FUNCIONARIO ADD CONSTRAINT FK_FUNMATRICULA_IN_TELEFONEFUNCIONARIO FOREIGN KEY (FUN_MATRICULA) REFERENCES FUNCIONARIO(MATRICULA);
/*FK (FUN_MATRICULA) REF. FUNCIONARIO(MATRICULA)*/
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_FUNMATRICULA_IN_DEPENDENTE FOREIGN KEY (FUN_MATRICULA) REFERENCES FUNCIONARIO(MATRICULA);
/*FK (FUN_MATRICULA) REF. FUNCIONARIO(MATRICULA)*/
ALTER TABLE MANUTENCAO ADD CONSTRAINT FK_FUNMATRICULA_IN_MANUTENCAO FOREIGN KEY (FUN_MATRICULA) REFERENCES FUNCIONARIO(MATRICULA);
/*FK (NUMERO_DO_CAIXA) REF. CAIXA(NUMERO_DO_CAIXA)*/
ALTER TABLE EQUIPAMENTO ADD CONSTRAINT FK_NUMCAIXA_IN_EQUIPAMENTO FOREIGN KEY (NUMERO_DO_CAIXA) REFERENCES CAIXA(NUMERO_DO_CAIXA);
/*FK (FIL_CODIGO) REF. FILIAL(CODIGO)*/
ALTER TABLE CAIXA ADD CONSTRAINT FK_FILCODIGO_IN_CAIXA FOREIGN KEY (FIL_CODIGO) REFERENCES FILIAL(CODIGO);
/*FK (CAI_NUMERO) REF. CAIXA(NUMERO_DO_CAIXA)*/
ALTER TABLE ORDEM_DE_COMPRA ADD CONSTRAINT FK_CAINUMERO_IN_ORDEMDECOMPRA FOREIGN KEY (CAI_NUMERO) REFERENCES CAIXA(NUMERO_DO_CAIXA);
/*FK (CLI_CPF) REF. CLIENTE(CPF)*/
ALTER TABLE ORDEM_DE_COMPRA ADD CONSTRAINT FK_CLICPF_IN_ORDEMDECOMPRA FOREIGN KEY (CLI_CPF) REFERENCES CLIENTE(CPF);
/*FK (FIL_CODIGO) REF. FILIAL(CODIGO)*/
ALTER TABLE ORDEM_DE_COMPRA ADD CONSTRAINT FK_FILCODIGO_IN_ORDEMDECOMPRA FOREIGN KEY (FIL_CODIGO) REFERENCES FILIAL(CODIGO);
/*FK (FUN_MATRICULA) REF. FUNCIONARIO(MATRICULA)*/
ALTER TABLE ORDEM_DE_COMPRA ADD CONSTRAINT FK_FUNMATRICULA_IN_ORDEMDECOMPRA FOREIGN KEY (FUN_MATRICULA) REFERENCES FUNCIONARIO(MATRICULA);
/*FK (ODC_NUMERO_NOTA) REF. ORDEM_DE_COMPRA(NUMERO_NOTA_FISCAL)*/
ALTER TABLE ITEM ADD CONSTRAINT FK_ODCNUMERONOTA_IN_ITEM FOREIGN KEY (ODC_NUMERO_NOTA) REFERENCES ORDEM_DE_COMPRA(NUMERO_NOTA_FISCAL);
/*FK (PRO_CODIGO_IDENTIFICACAO) REF. PRODUTO(CODIGO_DE_IDENTIFICACAO)*/
ALTER TABLE ITEM ADD CONSTRAINT FK_PRODCODIGOIDENTIFICACAO_IN_ITEM FOREIGN KEY (PRO_CODIGO_IDENTIFICACAO) REFERENCES PRODUTO(CODIGO_DE_IDENTIFICACAO);
/*FK (NTF_NUMERO) REF. NOTA_FISCAL(NUMERO)*/
ALTER TABLE ITEM ADD CONSTRAINT FK_NTFNUMERO_IN_ITEM FOREIGN KEY (NTF_NUMERO) REFERENCES NOTA_FISCAL(NUMERO);
/*FK (FIL_CODIGO) REF. FILIAL(CODIGO)*/
ALTER TABLE PRODUTO ADD CONSTRAINT FK_FILCODIGO_IN_PRODUTO FOREIGN KEY (FIL_CODIGO) REFERENCES FILIAL(CODIGO);
/*FK (CAT_IDENTIFICADOR) REF. CATEGORIA(IDENTIFICADOR)*/
ALTER TABLE PRODUTO ADD CONSTRAINT FK_CATIDENTIFICADOR_IN_PRODUTO FOREIGN KEY (CAT_IDENTIFICADOR) REFERENCES CATEGORIA(IDENTIFICADOR);
/*FK (MAR_IDENTIFICADOR) REF. MARCA(IDENTIFICADOR)*/
ALTER TABLE PRODUTO ADD CONSTRAINT FK_MARIDENTIFICADOR_IN_PRODUTO FOREIGN KEY (MAR_IDENTIFICADOR) REFERENCES MARCA(IDENTIFICADOR);
/*FK (CAT_IDENTIFICADOR) REF. CATEGORIA(IDENTIFICADOR)*/
ALTER TABLE FORNECEDOR ADD CONSTRAINT FK_CATIDENTIFICADOR_IN_FORNECEDOR FOREIGN KEY (CAT_IDENTIFICADOR) REFERENCES CATEGORIA(IDENTIFICADOR);
/*FK (SOL_IDENTIFICADOR) REF. SOLICITACAO(IDENTIFICADOR)*/
ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_SOLIDENTIFICADOR_IN_NOTAFISCAL FOREIGN KEY (SOL_IDENTIFICADOR) REFERENCES SOLICITACAO(IDENTIFICADOR);
/*FK (FIL_CODIGO) REF. FILIAL(CODIGO)*/
ALTER TABLE SOLICITACAO ADD CONSTRAINT FK_FILCODIGO_IN_SOLICITACAO FOREIGN KEY (FIL_CODIGO) REFERENCES FILIAL(CODIGO);
/*FK (FOR_CNPJ) REF. FORNECEDOR(CNPJ)*/
ALTER TABLE SOLICITACAO ADD CONSTRAINT FK_FORCNPJ_IN_SOLICITACAO FOREIGN KEY (FOR_CNPJ) REFERENCES FORNECEDOR(CNPJ);
/*FK (FOR_CNPJ) REF. FORNECEDOR(CNPJ)*/
ALTER TABLE TELEFONE_FORNECEDOR ADD CONSTRAINT FK_FORCNPJ_IN_TELEFONEFORNECEDOR FOREIGN KEY (FOR_CNPJ) REFERENCES FORNECEDOR(CNPJ);
/*FK (EQU_IDENTIFICADOR, NUMERO_DO_CAIXA) REF. EQUIPAMENTO(IDENTIFICADOR, NUMERO_DO_CAIXA)*/
ALTER TABLE MANUTENCAO ADD CONSTRAINT FK_EQUIDENTIFICADOR_E_NUMERODOCAIXA_IN_MANUTENCAO FOREIGN KEY (EQU_IDENTIFICADOR, NUMERO_DO_CAIXA) REFERENCES EQUIPAMENTO(IDENTIFICADOR, NUMERO_DO_CAIXA);


/*Exclusao das Tabelas*/

DROP TABLE CAIXA CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE DEPENDENTE CASCADE CONSTRAINTS;
DROP TABLE EQUIPAMENTO CASCADE CONSTRAINTS;
DROP TABLE FILIAL CASCADE CONSTRAINTS;
DROP TABLE FORNECEDOR CASCADE CONSTRAINTS;
DROP TABLE FUNCIONARIO CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE MANUTENCAO CASCADE CONSTRAINTS;
DROP TABLE MARCA CASCADE CONSTRAINTS;
DROP TABLE NOTA_FISCAL CASCADE CONSTRAINTS;
DROP TABLE ORDEM_DE_COMPRA CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP TABLE RECLAMACAO CASCADE CONSTRAINTS;
DROP TABLE SOLICITACAO CASCADE CONSTRAINTS;
DROP TABLE TELEFONE_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE TELEFONE_FORNECEDOR CASCADE CONSTRAINTS;
DROP TABLE TELEFONE_FUNCIONARIO CASCADE CONSTRAINTS;
